import Head from "next/head";
import type { NextPage } from "next";
import GluesatckUIProvider, { Box, Text, Button } from "@project/components";

const Meta = () => {
  return (
    <Head>
      <title>Create Gluestack App</title>
      <meta name="description" content="Generated by node glue add web" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

const Container = () => {
  return (
    <GluesatckUIProvider>
      <Box
        bg="$warning500"
        p="$20"
        justifyContent="center"
        alignItems="center">
        <Text color="$green500">Gluestack Web</Text>
        <Button>
          <Button.Text>Button</Button.Text>
        </Button>
      </Box>
    </GluesatckUIProvider>
  );
};

const Home: NextPage = () => {
  return (
    <div>
      <Meta />
      <Container />
    </div>
  );
};

export default Home;
